### PR TITLE
(patch) Update Polymer 2.x imports

### LINKED ISSUE #263: Update Polymer 2.x imports
Something that we missed in #258 was to update the html imports from `polymer.html` to `polymer-element.html`.

Will hopefully drop all legacy helpers (but might also highlight hidden dependencies on them).
As soon as this is merged I'll release v2.0.0

### PR DESCRIPTION
**Pull request by cristinecula**
I have updated each file with only the required imports.

Fixes #263

### CODE REVIEW

**Comment by cristinecula** [comment]
@megheaiulian

**Comment by nomego** [comment]
Great! Why do we need the legacy/class import?

**Comment by cristinecula** [comment]
For mixinBehaviors and for Polymer.Templatizer.

**Comment by cristinecula** [comment]
I'm not sure why the Travis build failed... I have run the tests locally and it's all good.

**Pull request merged**
