### PR TITLE
fix: cosmoz-omnitable, adding empty set message slot #23679

### PR DESCRIPTION
**Pull request by dotpointer**
Adding empty set message slot.

RM:23679.

### CODE REVIEW

**Review by nomego — COMMENTED** [review]
This change seems a bit weird, to have a slot with content where you can inject content.. don't they both get rendered?

**Comment by dotpointer** [comment]
> This change seems a bit weird, to have a slot with content where you can inject content.. don't they both get rendered?

The intent was to use the data in the slot as the default content. How shall it be done to achieve this?

**Comment by cristinecula** [comment]
@dotpointer what happens when you use the slot in the parent component? Is the default content replaced?

**Comment by dotpointer** [comment]
> @dotpointer what happens when you use the slot in the parent component? Is the default content replaced?

Yes this is how this PR works.

The slot data is passed from `upload.html.js`, through the parent slot in `list-core.html.js` to the slot in `cosmoz-omnitable.js`.

If you mean to only use the parent slot located in `upload.html.js` without this pull request with the slot in cosmoz-omnitable then this does not result in the upload text being shown.

**Comment by nomego** [comment]
Ok let's merge this if it visually addresses the issue, and let it be something to support/consider for the lit-omnitable version.
@dotpointer will you make sure the tests pass?

**Comment by dotpointer** [comment]
> Ok let's merge this if it visually addresses the issue, and let it be something to support/consider for the lit-omnitable version.
> @dotpointer will you make sure the tests pass?

Yes.

This seems to be the test result:

FAILED TESTS:
  visible
    ✖ adjusts columns when visible
      Firefox 80.0 (Ubuntu 0.0.0)
    expected true to be false

      + expected - actual

      -true
      +false

I checked the test at `basic.test.js`, why is it failing, I have not changed the visible columns?

**Comment by dotpointer** [comment]
I ran the tests locally, the test did not fail for me.

**Comment by dotpointer** [comment]
@nomego I restarted the tests, they do now seem to pass.

**Pull request merged**
