### PR TITLE
215 - Boolean column, fix to follow column data updates after table has been rendered

### PR DESCRIPTION
**Pull request by dotpointer**
Boolean column, fix to follow column data updates after table has been rendered, issue is #215 and #19683.

### CODE REVIEW

**Comment by dotpointer** [comment]
Please note: The XLSX errors are not due to the changes in this pull request. I tried to revert the pull request to only new line and the errors were still there (reverted and force pushed over the changes after it, therefore not present in commit log). Something is broken with the XLSX export.

**Comment by nomego** [comment]
Oh and however this PR turns out, it should be rebased to make tests pass and merge work.

**Comment by dotpointer** [comment]
Some kind of mix I think. Changed the order of the selections and made changes so `false` is `0` and `true` is `1` and rebased.

**Comment by nomego** [comment]
Can you just check to see if switching from "fallback-selection" to "selection" without changing anything else works before we merge this ?

**Comment by dotpointer** [comment]
Tested and seems to work, removed the unnecessary changes.

**Pull request merged**
