### PR TITLE
feature/AB9162

### PR DESCRIPTION
**Pull request by CarloBar1**
Task [AB#9162](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/9162/).
Change the aspect of omnitable headers so to look like this:
image

### CODE REVIEW

**Comment by CarloBar1** [comment]
The font-family attribute added doesn't seem to affect the placeholders in the header, just the "Boolean" field shown in the local development.

**Comment by CarloBar1** [comment]
Another update: I tried putting various font specifications around for the code, and in no case it was rendered, always keeping the default font.

**Comment by cristinecula** [comment]
Please rebase and squash the commits. Make sure that CI tests pass.

**Comment by cristinecula** [comment]
Can you find a way to make the font styles easier to edit from outside of the omnitable?
Either exposing the headers themselves as parts or using some css variables?
I think that it would make sense to be able to set `--cosmoz-omnitable-header-font` to customize all of the headers.

**Pull request closed without merging**
